// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enumpb/enum.proto

package enumpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DayOfTheWeek int32

const (
	DayOfTheWeek_UNKNOWN   DayOfTheWeek = 0
	DayOfTheWeek_MONDAY    DayOfTheWeek = 1
	DayOfTheWeek_TUESDAY   DayOfTheWeek = 2
	DayOfTheWeek_WEDNESDAY DayOfTheWeek = 3
	DayOfTheWeek_THURSDAY  DayOfTheWeek = 4
	DayOfTheWeek_FRIDAY    DayOfTheWeek = 5
	DayOfTheWeek_SATURDAY  DayOfTheWeek = 6
	DayOfTheWeek_SUNDAY    DayOfTheWeek = 7
)

var DayOfTheWeek_name = map[int32]string{
	0: "UNKNOWN",
	1: "MONDAY",
	2: "TUESDAY",
	3: "WEDNESDAY",
	4: "THURSDAY",
	5: "FRIDAY",
	6: "SATURDAY",
	7: "SUNDAY",
}
var DayOfTheWeek_value = map[string]int32{
	"UNKNOWN":   0,
	"MONDAY":    1,
	"TUESDAY":   2,
	"WEDNESDAY": 3,
	"THURSDAY":  4,
	"FRIDAY":    5,
	"SATURDAY":  6,
	"SUNDAY":    7,
}

func (x DayOfTheWeek) String() string {
	return proto.EnumName(DayOfTheWeek_name, int32(x))
}
func (DayOfTheWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_enum_c699fa6fd8d9e46b, []int{0}
}

type EnumMessage struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Day                  DayOfTheWeek `protobuf:"varint,2,opt,name=day,proto3,enum=enum.DayOfTheWeek" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_enum_c699fa6fd8d9e46b, []int{0}
}
func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (dst *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(dst, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnumMessage) GetDay() DayOfTheWeek {
	if m != nil {
		return m.Day
	}
	return DayOfTheWeek_UNKNOWN
}

func init() {
	proto.RegisterType((*EnumMessage)(nil), "enum.EnumMessage")
	proto.RegisterEnum("enum.DayOfTheWeek", DayOfTheWeek_name, DayOfTheWeek_value)
}

func init() { proto.RegisterFile("enumpb/enum.proto", fileDescriptor_enum_c699fa6fd8d9e46b) }

var fileDescriptor_enum_c699fa6fd8d9e46b = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcd, 0x2b, 0xcd,
	0x2d, 0x48, 0xd2, 0x07, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x92,
	0x33, 0x17, 0xb7, 0x6b, 0x5e, 0x69, 0xae, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x10, 0x1f,
	0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x0a,
	0x17, 0x73, 0x4a, 0x62, 0xa5, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x90, 0x1e, 0x58, 0xbb,
	0x4b, 0x62, 0xa5, 0x7f, 0x5a, 0x48, 0x46, 0x6a, 0x78, 0x6a, 0x6a, 0x76, 0x10, 0x48, 0x5a, 0xab,
	0x9c, 0x8b, 0x07, 0x59, 0x50, 0x88, 0x9b, 0x8b, 0x3d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f,
	0x80, 0x41, 0x88, 0x8b, 0x8b, 0xcd, 0xd7, 0xdf, 0xcf, 0xc5, 0x31, 0x52, 0x80, 0x11, 0x24, 0x11,
	0x12, 0xea, 0x1a, 0x0c, 0xe2, 0x30, 0x09, 0xf1, 0x72, 0x71, 0x86, 0xbb, 0xba, 0xf8, 0x41, 0xb8,
	0xcc, 0x42, 0x3c, 0x5c, 0x1c, 0x21, 0x1e, 0xa1, 0x41, 0x60, 0x1e, 0x0b, 0x48, 0x97, 0x5b, 0x90,
	0x27, 0x88, 0xcd, 0x0a, 0x92, 0x09, 0x76, 0x0c, 0x09, 0x0d, 0x02, 0xf1, 0xd8, 0x40, 0x32, 0xc1,
	0xa1, 0x60, 0xf3, 0xd8, 0x9d, 0x38, 0xa2, 0xd8, 0x20, 0x1e, 0x4b, 0x62, 0x03, 0x7b, 0xca, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x3d, 0x9e, 0x9b, 0xe9, 0x00, 0x00, 0x00,
}
